### PR TITLE
fix: Address Pre-Deployment Issues

### LINKED ISSUE #37: Fix URL References in Client
Update URL references in the front end when making web requests to it can be changed for deployment.

### LINKED ISSUE #38: Navbar Missing on Some Pages
The navbar is missing on some of the pages.

### LINKED ISSUE #39: Fix Client Page Routing
Some pages are missing routes or do not navigate between pages as expected.

### LINKED ISSUE #40: Fix Post Page Input Validation
The post page should have basic validation to let the user know what field is invalid. The client should also validate the user input before making a request to the back-end.

### PR DESCRIPTION
**Pull request by 3dxp**
- Clean up the project
- Fix some formatting issues
- Address API configuration for deploy time.

Note @zxkevin compleated the bulk of the PostList.js changes.

#39, #38, #37, #41

### CODE REVIEW

**Review by zxkevin — APPROVED** [review]
Looks good!

File: packages/hackmcx-client/src/AppNav.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+                    <Box sx={{ flexGrow: 1 }} />
+                    <Box sx={{ marginRight: 2 }}>
+                        <Link to={'/posts/create'}>
+                            <Button variant='contained' sx={{ mt: 2 }} >Create Post</Button>
+                        </Link>
+                    </Box>
+                    <Button variant='contained' sx={{ mt: 2}}>Sign In</Button>
+                </Toolbar>
+            </AppBar>
+            <Toolbar/>
```
Comment (3dxp) [inline packages/hackmcx-client/src/AppNav.js:28]: Grrr material UI...
